on: [pull_request]

name: Continuous integration

jobs:
  analyze:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --features=rkyv/size_32,zk,serde

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test:
    name: Run Tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make test

  build_benches:
    name: Build Benchmarks
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make build-benches

  no-std:
    name: Verify no_std + WASM compatibility
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make no-std
